//! OpenAPI aggregation + dev Swagger UI (KAIROS-T-0023, contract per
//! KAIROS-A-0005 §6).
//!
//! [`ApiDoc`] aggregates every `#[utoipa::path]`-annotated handler in the
//! crate — the spec derives from the same handlers and DTO types
//! (`kairos_client::types*`, A-0015) that serve traffic, so drift is
//! impossible by construction. The A-0012 gate rule ("a handler without
//! annotations fails review") is mechanized by `tests/openapi.rs`, which
//! asserts that the set of `(method, path)` pairs registered on the axum
//! routers equals the set the spec documents.
//!
//! # Routes
//!
//! - `GET /api/openapi.json` — the aggregated OpenAPI 3.x document.
//! - `GET /api/docs` — Swagger UI, mounted ONLY when
//!   [`crate::config::AppConfig::dev_ui`] is set (`KAIROS_DEV_UI=true`);
//!   the route does not exist in a default (production) configuration and
//!   is deliberately NOT part of the spec.
//!
//! # Authentication (decided here, KAIROS-T-0023)
//!
//! Both routes sit behind the standard auth → tenant middleware stack,
//! exactly like every other `/api` route: the spec enumerates the
//! deployment's full API surface and stays deployment-internal; any org
//! member can fetch it. The **unauthenticated** distribution channel is
//! the CI build artifact (`openapi.json` uploaded per run, A-0005 §6
//! "the spec is a CI artifact per release"), generated by the
//! `write_spec_artifact` test in `tests/openapi.rs` without a running
//! server. Dev Swagger UI callers authenticate like any API client
//! (curl, or a header-injecting browser extension in dev).
//!
//! # WebSocket channel
//!
//! OpenAPI covers the REST surface only. The `GET /ws/events` push
//! channel (A-0005 §5) is documented in `docs/api/events.md` and in the
//! [`crate::ws`] module docs; the spec's `info.description` points there.

use std::sync::LazyLock;

use axum::Router;
use axum::http::header;
use axum::response::{Html, IntoResponse};
use axum::routing::get;
use utoipa::OpenApi;

use crate::app::AppState;

/// The aggregated document: every annotated handler in the crate. Adding
/// an endpoint means adding its handler here — forgetting to do so fails
/// the route-vs-spec completeness test in `tests/openapi.rs`.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Kairos API",
        description = "The Kairos REST API (KAIROS-S-0005). Every route \
            requires a bearer token and a resolved tenant (subdomain, \
            `X-Tenant` header, or single-tenant mode) unless noted. \
            Real-time change notifications are NOT part of this spec: the \
            `GET /ws/events` WebSocket channel is documented in \
            `docs/api/events.md` (OpenAPI covers the REST surface only).",
    ),
    paths(
        // Entity families (KAIROS-T-0018).
        crate::api::strategies::list_strategies,
        crate::api::strategies::get_strategy,
        crate::api::strategies::create_strategy,
        crate::api::strategies::update_strategy,
        crate::api::strategies::delete_strategy,
        crate::api::strategies::transition_strategy,
        crate::api::initiatives::list_initiatives,
        crate::api::initiatives::get_initiative,
        crate::api::initiatives::create_initiative,
        crate::api::initiatives::update_initiative,
        crate::api::initiatives::delete_initiative,
        crate::api::initiatives::transition_initiative,
        crate::api::tasks::list_tasks,
        crate::api::tasks::get_task,
        crate::api::tasks::create_task,
        crate::api::tasks::update_task,
        crate::api::tasks::delete_task,
        crate::api::tasks::transition_task,
        crate::api::tasks::set_work_class,
        // Task repository binding (KAIROS-T-0104).
        crate::api::tasks::set_repository,
        crate::api::documents::list_documents,
        crate::api::documents::get_document,
        crate::api::documents::create_document,
        crate::api::documents::update_document,
        crate::api::documents::set_lifecycle,
        crate::api::documents::delete_document,
        crate::api::adrs::list_adrs,
        crate::api::adrs::get_adr,
        crate::api::adrs::create_adr,
        crate::api::adrs::update_adr,
        crate::api::adrs::delete_adr,
        crate::api::adrs::transition_adr,
        // Pre-delete cascade preview (KAIROS-T-0051).
        crate::api::cascade::cascade_preview,
        // Unified search (KAIROS-T-0021).
        crate::api::search::search,
        // Relationships / metadata / definitions / templates / history /
        // activity (KAIROS-T-0020).
        crate::api::meta::relationships::get_relationships,
        crate::api::meta::relationships::get_children_progress,
        crate::api::meta::relationships::get_item_graph,
        crate::api::meta::relationships::get_item_links,
        crate::api::meta::relationships::create_relationship,
        crate::api::meta::relationships::delete_relationship,
        crate::api::meta::metadata::get_metadata,
        crate::api::meta::metadata::update_metadata,
        crate::api::meta::definitions::list_definitions,
        crate::api::meta::definitions::create_definition,
        crate::api::meta::definitions::get_definition,
        crate::api::meta::definitions::update_definition,
        crate::api::meta::definitions::delete_definition,
        crate::api::meta::templates::list_templates,
        crate::api::meta::templates::get_template,
        crate::api::meta::templates::create_template,
        crate::api::meta::templates::update_template,
        crate::api::meta::templates::delete_template,
        crate::api::meta::history::get_history,
        crate::api::meta::activity::get_activity,
        // Organizational families (KAIROS-T-0019).
        crate::api::org::boards::list_boards,
        crate::api::org::boards::get_board,
        crate::api::org::boards::create_board,
        crate::api::org::boards::update_board,
        crate::api::org::boards::delete_board,
        crate::api::org::boards::board_items,
        crate::api::org::boards::list_columns,
        crate::api::org::boards::add_column,
        crate::api::org::boards::update_column,
        crate::api::org::boards::remove_column,
        crate::api::org::boards::list_transitions,
        crate::api::org::boards::add_transition,
        crate::api::org::boards::remove_transition,
        crate::api::org::boards::list_board_members,
        crate::api::org::boards::add_board_member,
        crate::api::org::boards::replace_capabilities,
        crate::api::org::boards::remove_board_member,
        crate::api::org::forge::list_connections,
        crate::api::org::forge::get_connection,
        crate::api::org::forge::create_connection,
        crate::api::org::forge::update_connection,
        crate::api::org::forge::delete_connection,
        crate::api::org::forge::rotate_connection,
        crate::api::org::teams::list_teams,
        crate::api::org::teams::get_team,
        crate::api::org::teams::get_team_by_slug,
        crate::api::org::teams::list_work_documents,
        crate::api::org::teams::list_team_links,
        crate::api::org::team_pages::list_pages,
        crate::api::org::team_pages::get_page,
        crate::api::org::team_pages::create_page,
        crate::api::org::team_pages::update_page,
        crate::api::org::team_pages::delete_page,
        crate::api::org::team_pages::list_announcements,
        crate::api::org::team_pages::create_announcement,
        crate::api::org::team_pages::delete_announcement,
        crate::api::org::teams::create_team,
        crate::api::org::teams::update_team,
        crate::api::org::teams::delete_team,
        crate::api::org::teams::list_members,
        crate::api::org::teams::add_member,
        crate::api::org::teams::remove_member,
        crate::api::org::streams::list_streams,
        crate::api::org::streams::get_stream,
        crate::api::org::streams::create_stream,
        crate::api::org::streams::update_stream,
        crate::api::org::streams::delete_stream,
        crate::api::org::streams::list_stream_teams,
        crate::api::org::streams::add_stream_team,
        crate::api::org::streams::remove_stream_team,
        crate::api::org::members::list_members,
        crate::api::org::members::add_member,
        crate::api::org::members::update_member,
        crate::api::org::members::remove_member,
        // Cross-tenant deployment admin (KAIROS-T-0019).
        crate::api::org::admin::list_tenants,
        crate::api::org::admin::create_tenant,
        crate::api::org::admin::delete_tenant,
        // SCIM token management (KAIROS-T-0025; annotated at orchestrator merge).
        crate::scim::tokens::create_token,
        crate::scim::tokens::list_tokens,
        crate::scim::tokens::revoke_token,
        // Service-account + API-key management (KAIROS-T-0059, A-0017).
        crate::service_accounts::routes::create_service_account,
        crate::service_accounts::routes::list_service_accounts,
        crate::service_accounts::routes::delete_service_account,
        crate::service_accounts::routes::create_key,
        crate::service_accounts::routes::list_keys,
        crate::service_accounts::routes::revoke_key,
        // This module + the app.rs whoami probe (doc stub below).
        openapi_json,
        whoami,
        // GUI auth support (KAIROS-T-0039; handlers in crate::web —
        // doc stubs below, the whoami pattern).
        spa_config,
        token_relay,
    ),
)]
struct ApiDoc;

/// The aggregated OpenAPI document (also consumed by `tests/openapi.rs`,
/// whose `write_spec_artifact` test generates the CI artifact).
pub fn spec() -> utoipa::openapi::OpenApi {
    ApiDoc::openapi()
}

/// The serialized spec, built once per process.
static SPEC_JSON: LazyLock<String> = LazyLock::new(|| {
    serde_json::to_string_pretty(&spec()).expect("the derived OpenAPI document serializes")
});

/// Build the module's routes. Merged into the protected `/api` chain by
/// [`crate::app::router`] (behind auth → tenant, see module docs);
/// `dev_ui` comes from [`crate::config::AppConfig::dev_ui`].
pub fn router(dev_ui: bool) -> Router<AppState> {
    let router = Router::new().route("/api/openapi.json", get(openapi_json));
    if dev_ui {
        router.route("/api/docs", get(swagger_ui))
    } else {
        router
    }
}

/// Serve the aggregated spec.
#[utoipa::path(
    get,
    path = "/api/openapi.json",
    tag = "meta",
    responses(
        (status = 200, description = "This OpenAPI 3.x document (application/json)"),
        (status = 401, description = "Missing/invalid token", body = kairos_client::types::ErrorEnvelope),
        (status = 403, description = "Not a member of the organization", body = kairos_client::types::ErrorEnvelope),
    ),
)]
pub(crate) async fn openapi_json() -> impl IntoResponse {
    (
        [(header::CONTENT_TYPE, "application/json")],
        SPEC_JSON.as_str(),
    )
}

/// Doc-stub for `GET /api/whoami`: the handler lives in [`crate::app`]
/// (T-0017's middleware probe), outside the api tree, and its response
/// types predate the shared DTO crate — so the spec documents the route
/// here without a response schema. Never called; it exists only for the
/// `#[utoipa::path]` expansion referenced by [`ApiDoc`].
#[allow(dead_code)]
#[utoipa::path(
    get,
    path = "/api/whoami",
    tag = "meta",
    responses(
        (
            status = 200,
            description = "The authenticated user, the resolved organization \
                and the caller's role in it, the caller's teams, and the \
                caller's board-scoped capability grants (KAIROS-A-0006, \
                grouped by board) \
                (`crate::app::WhoamiResponse`: `{user: {id, external_id, \
                email, display_name}, organization: {id, slug, role}, \
                teams: [{id, slug, name}], capabilities: [{board_id, \
                board_slug, grants: [..]}]}`)",
        ),
        (status = 401, description = "Missing/invalid token", body = kairos_client::types::ErrorEnvelope),
        (status = 403, description = "Not a member of the organization", body = kairos_client::types::ErrorEnvelope),
    ),
)]
fn whoami() {}

/// Doc-stub for `GET /api/config` (KAIROS-T-0039): the handler lives in
/// [`crate::web`]. PUBLIC (no auth): it is the SPA's discovery endpoint —
/// exactly the information a login page needs before any token exists.
#[allow(dead_code)]
#[utoipa::path(
    get,
    path = "/api/config",
    tag = "meta",
    responses(
        (
            status = 200,
            description = "SPA login configuration (public): `{issuer, \
                client_id, authorization_endpoint, api_bearer}` — the \
                deployment issuer, the GUI's OAuth client id \
                (KAIROS_WEB_CLIENT_ID), the issuer's authorization endpoint \
                from OIDC discovery, and which token the SPA sends as the \
                `/api` bearer (`access_token` default, or `id_token` for \
                opaque-access-token issuers like Google Workspace, \
                KAIROS-T-0054)",
        ),
        (status = 502, description = "The configured issuer is unreachable", body = kairos_client::types::ErrorEnvelope),
    ),
)]
fn spa_config() {}

/// Doc-stub for `POST /api/auth/token` (KAIROS-T-0039): the handler lives
/// in [`crate::web`]. PUBLIC (pre-login by nature): the same-origin relay
/// to the issuer's token endpoint for the SPA's PKCE code exchange and
/// refresh grant (IdP token endpoints rarely serve CORS).
#[allow(dead_code)]
#[utoipa::path(
    post,
    path = "/api/auth/token",
    tag = "meta",
    request_body(
        content_type = "application/x-www-form-urlencoded",
        description = "grant_type=authorization_code (+ code, redirect_uri, \
            code_verifier) or grant_type=refresh_token (+ refresh_token); \
            client_id is always replaced with the server-configured one",
    ),
    responses(
        (status = 200, description = "The issuer's token response, passed through"),
        (status = 400, description = "The issuer rejected the grant (OAuth error JSON, passed through)"),
        (status = 422, description = "Unsupported grant_type or missing field", body = kairos_client::types::ErrorEnvelope),
        (status = 502, description = "The configured issuer is unreachable", body = kairos_client::types::ErrorEnvelope),
    ),
)]
fn token_relay() {}

/// The dev-only Swagger UI page (`KAIROS_DEV_UI=true`). A single
/// self-contained HTML page that loads the pinned `swagger-ui-dist`
/// bundle from a CDN and points it at `/api/openapi.json` — no extra
/// crate dependency, no UI assets embedded in the production binary
/// (the flag only controls route presence; this is a dev tool, and dev
/// machines have network access).
pub(crate) async fn swagger_ui() -> Html<&'static str> {
    Html(SWAGGER_UI_HTML)
}

/// Kept minimal on purpose: the page is behind the same auth → tenant
/// stack as the spec (module docs), so it is reached with an
/// authenticated client; requests issued from "Try it out" inherit that
/// client's headers.
const SWAGGER_UI_HTML: &str = r##"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Kairos API — Swagger UI</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui.css" />
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui-bundle.js"></script>
  <script>
    window.ui = SwaggerUIBundle({
      url: "/api/openapi.json",
      dom_id: "#swagger-ui",
      deepLinking: true,
      presets: [SwaggerUIBundle.presets.apis],
    });
  </script>
</body>
</html>
"##;
