//! KAIROS-T-0023 — OpenAPI aggregation (`/api/openapi.json`) and the dev
//! Swagger UI (`/api/docs`, `KAIROS_DEV_UI`).
//!
//! # The route-vs-spec completeness test (A-0005 §6 / A-0012 enforcement)
//!
//! axum's `Router` cannot be introspected, so completeness is asserted in
//! two mechanized halves:
//!
//! 1. [`registered_routes_and_spec_paths_match_exactly`] (no services
//!    needed) scans this crate's `src/` for `.route("...", ...)`
//!    registrations, extracts every `(method, path)` pair under `/api`,
//!    and asserts SET EQUALITY with the `(method, path)` pairs the spec
//!    documents. **Failure mode**: a new route registered anywhere in
//!    `src/` without a `#[utoipa::path]` handler wired into
//!    `api::openapi::ApiDoc` fails this test (it appears in the
//!    registered set but not the spec), as does a spec entry whose route
//!    was never registered. Blind spot: a route registered through
//!    something other than a `.route("literal", ...)` call would escape
//!    the scan — the probe below catches the documented-but-unmounted
//!    half, and this crate registers routes exclusively via `.route`.
//! 2. The probe inside [`openapi_endpoint_against_live_stack`] walks
//!    every path in the served spec against the REAL production router
//!    and asserts a non-404 answer (an unauthenticated request reaches
//!    the auth layer only if the route exists; the bare-router fallback
//!    is the only 404 source for a token-less request). This catches a
//!    scanned-and-documented route whose module router was never merged
//!    into `app::router`. It cannot catch method drift (the auth layer
//!    answers 401 before method dispatch) — half 1 owns methods.
//!
//! The CI artifact is generated by [`write_spec_artifact`] (pure, no
//! services), uploaded by the workflow's "OpenAPI artifact" step.

mod common;

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path as FsPath, PathBuf};
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Method, Request, StatusCode};
use diesel::prelude::*;
use http_body_util::BodyExt;
use serde_json::Value;
use tower::ServiceExt;
use uuid::Uuid;

use common::{
    AUDIENCE, ISSUER, base_config, drop_scratch_db, error_code, recreate_scratch_db, request,
    user_token, with_database,
};
use kairos_db::models::{NewOrganizationMember, OrgRole};
use kairos_db::schema::{organization_members, organizations, users};
use kairos_db::{TenantPool, provision_tenant, run_public_migrations};
use kairos_server::api::openapi::spec;
use kairos_server::app;
use kairos_server::middleware::auth::Authenticator;

/// Uniquely named scratch database for this test binary.
const SCRATCH_DB: &str = "kairos_openapi_t0023_test";

/// Every request resolves the tenant via the X-Tenant fallback.
const TENANT_HEADERS: &[(&str, &str)] = &[("x-tenant", "acme")];

/// Routes that exist on (some configuration of) the router but are
/// deliberately NOT documented in the spec. Each entry needs a reason.
const EXCLUDED_FROM_SPEC: &[(&str, &str, &str)] = &[(
    "GET",
    "/api/docs",
    "dev-only Swagger UI (KAIROS_DEV_UI); absent from production routers",
)];

// ---------------------------------------------------------------------------
// Source scan: the registered (method, path) set
// ---------------------------------------------------------------------------

/// Collect every `.rs` file under `dir`, recursively.
fn rust_sources(dir: &FsPath, out: &mut Vec<PathBuf>) {
    for entry in std::fs::read_dir(dir).expect("readable src dir") {
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            rust_sources(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

/// The argument text of one `.route(` call: everything up to the paren
/// that balances the opening one, plus how many bytes were consumed.
fn balanced_args(text: &str) -> (&str, usize) {
    let mut depth = 1usize;
    for (i, c) in text.char_indices() {
        match c {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    return (&text[..i], i);
                }
            }
            _ => {}
        }
    }
    panic!("unbalanced .route( arguments: {text:?}");
}

/// The HTTP methods named in a `.route(...)` argument list: `get(`,
/// `post(`, ... tokens not preceded by an identifier character (so
/// `get(get_strategy)` counts `get` once and ignores the handler name).
fn methods_in(args: &str) -> Vec<String> {
    let mut methods = Vec::new();
    for method in ["get", "post", "put", "patch", "delete", "head", "options"] {
        let needle = format!("{method}(");
        let mut from = 0;
        while let Some(pos) = args[from..].find(&needle) {
            let at = from + pos;
            let preceded_by_ident = at > 0
                && args[..at]
                    .chars()
                    .next_back()
                    .is_some_and(|c| c.is_alphanumeric() || c == '_');
            if !preceded_by_ident {
                methods.push(method.to_uppercase());
            }
            from = at + needle.len();
        }
    }
    methods.sort();
    methods.dedup();
    methods
}

/// Scan the crate's `src/` for `.route("literal", ...)` registrations and
/// return every `(METHOD, path)` pair whose path starts with `/api`.
/// Comment lines are stripped so doc examples cannot pollute the set.
fn registered_api_routes() -> BTreeSet<(String, String)> {
    let src = FsPath::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut files = Vec::new();
    rust_sources(&src, &mut files);
    assert!(!files.is_empty(), "no sources under {src:?}");

    let mut routes = BTreeSet::new();
    for file in &files {
        // src/mcp is quarantined (unmounted) pending KAIROS-T-0026 resume; its
        // routes are non-/api MCP protocol surface and use const paths this
        // literal scanner cannot read. T-0026 must either keep its routes
        // outside /api (they are) or extend this scanner when un-quarantining.
        if file.components().any(|c| c.as_os_str() == "mcp") {
            continue;
        }
        let raw = std::fs::read_to_string(file).expect("readable source file");
        let code: String = raw
            .lines()
            .filter(|line| !line.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        let mut rest = code.as_str();
        while let Some(pos) = rest.find(".route(") {
            let args_start = pos + ".route(".len();
            let (args, consumed) = balanced_args(&rest[args_start..]);
            let path = args
                .split('"')
                .nth(1)
                .unwrap_or_else(|| panic!("{file:?}: .route( without a path literal: {args:?}"));
            if path.starts_with("/api") {
                let methods = methods_in(args);
                assert!(
                    !methods.is_empty(),
                    "{file:?}: no methods recognized in .route({args:?})"
                );
                for method in methods {
                    routes.insert((method, path.to_string()));
                }
            }
            rest = &rest[args_start + consumed..];
        }
    }
    routes
}

/// The `(METHOD, path)` pairs the aggregated spec documents.
fn documented_api_routes(spec_json: &Value) -> BTreeSet<(String, String)> {
    let paths = spec_json["paths"]
        .as_object()
        .expect("spec has a paths object");
    let mut routes = BTreeSet::new();
    for (path, item) in paths {
        for method in item.as_object().expect("path item object").keys() {
            match method.as_str() {
                "get" | "post" | "put" | "patch" | "delete" | "head" | "options" | "trace" => {
                    routes.insert((method.to_uppercase(), path.clone()));
                }
                // parameters/summary/description keys are not operations.
                _ => {}
            }
        }
    }
    routes
}

// ---------------------------------------------------------------------------
// Pure tests (no services)
// ---------------------------------------------------------------------------

/// THE completeness gate (module docs): registered routes == spec paths.
#[test]
fn registered_routes_and_spec_paths_match_exactly() {
    let spec_json = serde_json::to_value(spec()).expect("spec serializes");
    let mut registered = registered_api_routes();
    for (method, path, _reason) in EXCLUDED_FROM_SPEC {
        assert!(
            registered.remove(&(method.to_string(), path.to_string())),
            "stale EXCLUDED_FROM_SPEC entry: {method} {path} is not registered anywhere"
        );
    }
    let documented = documented_api_routes(&spec_json);

    let missing_from_spec: Vec<_> = registered.difference(&documented).collect();
    let missing_from_router: Vec<_> = documented.difference(&registered).collect();
    assert!(
        missing_from_spec.is_empty() && missing_from_router.is_empty(),
        "route/spec drift (A-0005 §6).\n\
         Registered but NOT in the OpenAPI spec (annotate the handler with \
         #[utoipa::path] and add it to api::openapi::ApiDoc): {missing_from_spec:?}\n\
         In the spec but NOT registered on any router: {missing_from_router:?}"
    );
}

/// The spec is 3.x and covers every expected path family (spot list —
/// the exact-set test above is the real gate; this documents intent).
#[test]
fn spec_is_openapi_3_and_covers_expected_families() {
    let spec_json = serde_json::to_value(spec()).expect("spec serializes");
    let version = spec_json["openapi"].as_str().expect("openapi version");
    assert!(version.starts_with("3."), "expected 3.x, got {version}");

    let paths = spec_json["paths"].as_object().expect("paths object");
    for expected in [
        "/api/strategies",
        "/api/strategies/{short_code}",
        "/api/strategies/{short_code}/transition",
        "/api/initiatives",
        "/api/tasks",
        "/api/documents",
        "/api/adrs",
        "/api/search",
        "/api/boards",
        "/api/boards/{id}/items",
        "/api/teams",
        "/api/delivery-streams",
        "/api/members",
        "/api/relationships",
        "/api/{entity_type}/{short_code}/relationships",
        "/api/{entity_type}/{short_code}/metadata",
        "/api/{entity_type}/{short_code}/history",
        "/api/metadata-definitions",
        "/api/templates",
        "/api/activity",
        "/api/admin/tenants",
        "/api/whoami",
        "/api/openapi.json",
    ] {
        assert!(paths.contains_key(expected), "spec is missing {expected}");
    }
    // The dev UI is deliberately undocumented (EXCLUDED_FROM_SPEC).
    assert!(!paths.contains_key("/api/docs"));

    // DTO schemas were aggregated (the deep resolution check is the
    // containerized validator run recorded in KAIROS-T-0023).
    let schemas = spec_json["components"]["schemas"]
        .as_object()
        .expect("components.schemas");
    for expected in ["Strategy", "Task", "SearchRequest", "ErrorEnvelope"] {
        assert!(
            schemas.contains_key(expected),
            "components.schemas is missing {expected}"
        );
    }
}

/// operationIds must be unique across the aggregated document.
#[test]
fn operation_ids_are_unique() {
    let spec_json = serde_json::to_value(spec()).expect("spec serializes");
    let mut seen: BTreeMap<String, (String, String)> = BTreeMap::new();
    for (method, path) in documented_api_routes(&spec_json) {
        let id = spec_json["paths"][&path][method.to_lowercase()]["operationId"]
            .as_str()
            .unwrap_or_else(|| panic!("{method} {path} has no operationId"))
            .to_string();
        if let Some(previous) = seen.insert(id.clone(), (method.clone(), path.clone())) {
            panic!("duplicate operationId {id:?}: {previous:?} vs ({method}, {path})");
        }
    }
}

/// Generate the CI artifact: write the spec to `target/openapi.json`
/// (workspace target dir). The CI workflow runs exactly this test and
/// uploads the file; the containerized validator runs against it too.
#[test]
fn write_spec_artifact() {
    let out = FsPath::new(env!("CARGO_MANIFEST_DIR")).join("../../target/openapi.json");
    let json = serde_json::to_string_pretty(&spec()).expect("spec serializes");
    std::fs::write(&out, &json).expect("writable target dir");
    // Round-trip: what CI uploads is parseable JSON.
    let parsed: Value = serde_json::from_str(&json).expect("artifact parses");
    assert!(parsed["openapi"].as_str().is_some());
    println!("wrote {}", out.display());
}

// ---------------------------------------------------------------------------
// Integration: the served endpoint + dev Swagger UI (live stack)
// ---------------------------------------------------------------------------

/// A raw in-process request for non-JSON responses (the Swagger UI page):
/// status, `content-type`, body text.
async fn raw_get(router: &Router, uri: &str, token: Option<&str>) -> (StatusCode, String, String) {
    let mut builder = Request::builder().method(Method::GET).uri(uri);
    if let Some(token) = token {
        builder = builder.header("authorization", format!("Bearer {token}"));
    }
    let response = router
        .clone()
        .oneshot(
            builder
                .header("x-tenant", "acme")
                .body(Body::empty())
                .expect("request"),
        )
        .await
        .expect("response");
    let status = response.status();
    let content_type = response
        .headers()
        .get("content-type")
        .map(|v| v.to_str().unwrap_or_default().to_string())
        .unwrap_or_default();
    let bytes = response
        .into_body()
        .collect()
        .await
        .expect("body")
        .to_bytes();
    (status, content_type, String::from_utf8_lossy(&bytes).into())
}

/// Substitute every `{param}` in a spec path with a literal segment so it
/// matches the axum route pattern (the probe never reaches a handler, so
/// the value is irrelevant).
fn probe_uri(spec_path: &str) -> String {
    spec_path
        .split('/')
        .map(|segment| {
            if segment.starts_with('{') && segment.ends_with('}') {
                "probe"
            } else {
                segment
            }
        })
        .collect::<Vec<_>>()
        .join("/")
}

#[tokio::test]
async fn openapi_endpoint_against_live_stack() {
    // --- scratch database + tenant -------------------------------------------
    let mut admin_conn = recreate_scratch_db(SCRATCH_DB);
    let scratch_url = with_database(&common::admin_database_url(), SCRATCH_DB);
    let mut conn = PgConnection::establish(&scratch_url).expect("connecting to scratch database");
    run_public_migrations(&mut conn).expect("running public migrations");
    provision_tenant(&mut conn, "acme", "Acme Inc").expect("provisioning acme");
    let org_id: Uuid = organizations::table
        .filter(organizations::slug.eq("acme"))
        .select(organizations::id)
        .first(&mut conn)
        .expect("acme org row");

    // --- production router + live token ---------------------------------------
    let http = reqwest::Client::new();
    let alice = user_token(&http, "alice").await;
    let pool = TenantPool::new(&scratch_url, 4).await.expect("pool");
    let auth = Arc::new(
        Authenticator::discover(ISSUER, AUDIENCE)
            .await
            .expect("OIDC discovery against live Dex"),
    );
    // KAIROS-T-0203: local auth ON for the probe below. `/api/login` and
    // `/api/logout` are documented unconditionally — the spec is the API contract —
    // but they are ROUTED only when KAIROS_LOCAL_AUTH is on. A probe router with
    // them off would report them as documented-but-unrouted, which is the very
    // drift this test exists to catch, so the router under probe is the one that
    // has every documented route.
    let mut probe_config = base_config(&scratch_url);
    probe_config.local_auth = true;
    let router = app::router(app::state_with(probe_config, pool.clone(), auth.clone()));

    // --- auth posture: the spec sits behind the standard stack ---------------
    let (status, body) = request(
        &router,
        Method::GET,
        "/api/openapi.json",
        None,
        TENANT_HEADERS,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::UNAUTHORIZED, "{body}");
    assert_eq!(error_code(&body), "UNAUTHORIZED");

    // First authenticated request JIT-provisions alice; she is not an org
    // member yet, so membership 403 — then grant it.
    let (status, body) = request(
        &router,
        Method::GET,
        "/api/openapi.json",
        Some(&alice),
        TENANT_HEADERS,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::FORBIDDEN, "{body}");
    assert_eq!(error_code(&body), "MEMBERSHIP_REQUIRED");
    let alice_id: Uuid = users::table
        .filter(users::email.eq("alice@kairos.test"))
        .select(users::id)
        .first(&mut conn)
        .expect("alice provisioned");
    diesel::insert_into(organization_members::table)
        .values(NewOrganizationMember {
            organization_id: org_id,
            user_id: alice_id,
            role: OrgRole::Member,
        })
        .execute(&mut conn)
        .expect("granting alice membership");

    // --- GET /api/openapi.json: 3.x, byte-identical to the aggregation -------
    let (status, served) = request(
        &router,
        Method::GET,
        "/api/openapi.json",
        Some(&alice),
        TENANT_HEADERS,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::OK, "{served}");
    let version = served["openapi"].as_str().expect("openapi version");
    assert!(version.starts_with("3."), "expected 3.x, got {version}");
    assert_eq!(
        served,
        serde_json::to_value(spec()).expect("spec serializes"),
        "the served document must be exactly the aggregated spec"
    );
    for family in ["/api/strategies", "/api/search", "/api/boards"] {
        assert!(
            served["paths"].get(family).is_some(),
            "served spec is missing {family}"
        );
    }

    // --- probe: every documented path exists on the production router --------
    // Token-less requests 404 ONLY from the bare-router fallback (matched
    // routes answer 401 from the auth layer first) — see module docs.
    for (method, path) in documented_api_routes(&served) {
        let uri = probe_uri(&path);
        let (status, _body) = request(
            &router,
            Method::from_bytes(method.as_bytes()).expect("method"),
            &uri,
            None,
            &[],
            None,
        )
        .await;
        assert_ne!(
            status,
            StatusCode::NOT_FOUND,
            "{method} {path} is documented in the spec but not routed \
             (probe {uri} hit the router fallback)"
        );
    }

    // --- Swagger UI: present with KAIROS_DEV_UI, absent by default -----------
    let mut dev_config = base_config(&scratch_url);
    dev_config.dev_ui = true;
    let dev_router = app::router(app::state_with(dev_config, pool, auth));

    let (status, content_type, page) = raw_get(&dev_router, "/api/docs", Some(&alice)).await;
    assert_eq!(status, StatusCode::OK, "{page}");
    assert!(content_type.starts_with("text/html"), "{content_type}");
    assert!(page.contains("SwaggerUIBundle"), "{page}");
    assert!(page.contains("/api/openapi.json"), "{page}");

    let (status, _, _) = raw_get(&router, "/api/docs", Some(&alice)).await;
    assert_eq!(
        status,
        StatusCode::NOT_FOUND,
        "/api/docs must not exist without KAIROS_DEV_UI"
    );

    drop_scratch_db(&mut admin_conn, SCRATCH_DB);
}
