// @generated by `angreal db schema-sync` (diesel print-schema, two passes).
// Do not edit by hand - edit migrations and re-run schema-sync.
//
// Layout (KAIROS-A-0009 single schema.rs, KAIROS-T-0009):
//   1. Tenant tables: UNQUALIFIED - resolved at runtime through the
//      connection's search_path (`org_{slug}, public`; see
//      kairos_db::pool). Generated against a throwaway migrated
//      tenant schema (org_schema_sync_template).
//   2. Public tables: SCHEMA-QUALIFIED (`public.*`) so they resolve
//      no matter which tenant search_path is pinned.

pub mod sql_types {
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "vector"))]
    pub struct Vector;
}

diesel::table! {
    activity_log (id) {
        id -> Uuid,
        actor_id -> Uuid,
        action -> Text,
        entity_id -> Nullable<Uuid>,
        entity_type -> Nullable<Text>,
        details -> Text,
        occurred_at -> Timestamptz,
    }
}

diesel::table! {
    adrs (id) {
        id -> Uuid,
        short_code -> Text,
        title -> Text,
        content -> Text,
        board_id -> Nullable<Uuid>,
        column_id -> Nullable<Uuid>,
        decision_maker -> Nullable<Text>,
        decision_date -> Nullable<Date>,
        version -> Int4,
        created_by -> Uuid,
        updated_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    api_keys (id) {
        id -> Uuid,
        user_id -> Uuid,
        name -> Text,
        token_hash -> Text,
        prefix -> Text,
        created_by -> Uuid,
        created_at -> Timestamptz,
        expires_at -> Nullable<Timestamptz>,
        last_used_at -> Nullable<Timestamptz>,
        revoked_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    board_columns (id) {
        id -> Uuid,
        board_id -> Uuid,
        name -> Text,
        position -> Int4,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        is_done -> Bool,
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    board_member_capabilities (board_id, user_id, capability) {
        board_id -> Uuid,
        user_id -> Uuid,
        capability -> Text,
        granted_at -> Timestamptz,
        granted_by -> Uuid,
    }
}

diesel::table! {
    board_transitions (id) {
        id -> Uuid,
        board_id -> Uuid,
        from_column_id -> Uuid,
        to_column_id -> Uuid,
    }
}

diesel::table! {
    boards (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        board_level -> Text,
        team_id -> Nullable<Uuid>,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    delivery_streams (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        description -> Nullable<Text>,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    documents (id) {
        id -> Uuid,
        short_code -> Text,
        title -> Text,
        content -> Text,
        template_id -> Nullable<Uuid>,
        version -> Int4,
        created_by -> Uuid,
        updated_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        lifecycle -> Text,
    }
}

diesel::table! {
    edge_proposals (id) {
        id -> Uuid,
        source_id -> Uuid,
        target_id -> Uuid,
        relationship -> Text,
        state -> Text,
        claim -> Text,
        why -> Text,
        score -> Float4,
        proposed_by -> Uuid,
        decided_by -> Nullable<Uuid>,
        decided_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    forge_connections (id) {
        id -> Uuid,
        forge -> Text,
        created_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        repository_id -> Uuid,
    }
}

diesel::table! {
    initiatives (id) {
        id -> Uuid,
        short_code -> Text,
        title -> Text,
        content -> Text,
        board_id -> Uuid,
        column_id -> Uuid,
        complexity -> Nullable<Text>,
        is_bucket -> Bool,
        bucket_type -> Nullable<Text>,
        version -> Int4,
        created_by -> Uuid,
        updated_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::Vector;

    item_chunks (id) {
        id -> Uuid,
        item_id -> Uuid,
        entity_type -> Text,
        ordinal -> Int4,
        heading -> Nullable<Text>,
        char_start -> Int4,
        char_end -> Int4,
        chunk_text -> Text,
        embedding -> Vector,
        provider -> Text,
        model -> Text,
        dimension -> Int4,
        content_hash -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::Vector;

    item_embeddings (item_id) {
        item_id -> Uuid,
        entity_type -> Text,
        embedding -> Vector,
        provider -> Text,
        model -> Text,
        dimension -> Int4,
        content_hash -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    item_history (id) {
        id -> Uuid,
        item_id -> Uuid,
        version -> Int4,
        title -> Text,
        content -> Text,
        edited_by -> Uuid,
        edited_at -> Timestamptz,
    }
}

diesel::table! {
    item_links (id) {
        id -> Uuid,
        item_id -> Uuid,
        connection_id -> Uuid,
        kind -> Text,
        external_id -> Text,
        title -> Text,
        url -> Text,
        state -> Text,
        author -> Text,
        forge_updated_at -> Timestamptz,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    item_metadata (id) {
        id -> Uuid,
        item_id -> Uuid,
        metadata_definition_id -> Uuid,
        value -> Text,
    }
}

diesel::table! {
    item_relationships (id) {
        id -> Uuid,
        source_id -> Uuid,
        target_id -> Uuid,
        relationship -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    metadata_definition_scopes (metadata_definition_id, entity_type) {
        metadata_definition_id -> Uuid,
        entity_type -> Text,
    }
}

diesel::table! {
    metadata_definitions (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        field_type -> Text,
        is_system_default -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    metadata_enum_options (id) {
        id -> Uuid,
        metadata_definition_id -> Uuid,
        value -> Text,
        position -> Int4,
    }
}

diesel::table! {
    repositories (id) {
        id -> Uuid,
        slug -> Text,
        forge -> Text,
        repo_full_name -> Text,
        repo_url -> Text,
        default_branch -> Text,
        team_id -> Uuid,
        description -> Text,
        created_by -> Uuid,
        updated_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    scim_tokens (id) {
        id -> Uuid,
        name -> Text,
        token_hash -> Text,
        created_by -> Uuid,
        created_at -> Timestamptz,
        revoked_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    strategies (id) {
        id -> Uuid,
        short_code -> Text,
        title -> Text,
        content -> Text,
        board_id -> Uuid,
        column_id -> Uuid,
        hypothesis -> Nullable<Text>,
        version -> Int4,
        created_by -> Uuid,
        updated_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    tasks (id) {
        id -> Uuid,
        short_code -> Text,
        title -> Text,
        content -> Text,
        board_id -> Uuid,
        column_id -> Uuid,
        task_type -> Text,
        team_id -> Nullable<Uuid>,
        version -> Int4,
        created_by -> Uuid,
        updated_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        work_class -> Text,
        repository_id -> Nullable<Uuid>,
    }
}

diesel::table! {
    team_announcements (id) {
        id -> Uuid,
        team_id -> Uuid,
        body -> Text,
        pinned -> Bool,
        created_by -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    team_delivery_streams (team_id, delivery_stream_id) {
        team_id -> Uuid,
        delivery_stream_id -> Uuid,
    }
}

diesel::table! {
    team_members (team_id, user_id) {
        team_id -> Uuid,
        user_id -> Uuid,
        joined_at -> Timestamptz,
    }
}

diesel::table! {
    team_page_history (id) {
        id -> Uuid,
        page_id -> Uuid,
        version -> Int4,
        title -> Text,
        content -> Text,
        edited_by -> Uuid,
        edited_at -> Timestamptz,
    }
}

diesel::table! {
    team_pages (id) {
        id -> Uuid,
        team_id -> Uuid,
        parent_id -> Nullable<Uuid>,
        kind -> Text,
        slug -> Text,
        title -> Text,
        content -> Text,
        position -> Int4,
        is_protected -> Bool,
        version -> Int4,
        created_by -> Uuid,
        updated_by -> Uuid,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    teams (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        team_type -> Text,
        deleted_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    template_metadata (id) {
        id -> Uuid,
        template_id -> Uuid,
        metadata_definition_id -> Uuid,
        default_value -> Nullable<Text>,
        required -> Bool,
    }
}

diesel::table! {
    templates (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        content -> Text,
        is_system_default -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(adrs -> board_columns (column_id));
diesel::joinable!(adrs -> boards (board_id));
diesel::joinable!(board_columns -> boards (board_id));
diesel::joinable!(board_member_capabilities -> boards (board_id));
diesel::joinable!(board_transitions -> boards (board_id));
diesel::joinable!(boards -> teams (team_id));
diesel::joinable!(documents -> templates (template_id));
diesel::joinable!(forge_connections -> repositories (repository_id));
diesel::joinable!(initiatives -> board_columns (column_id));
diesel::joinable!(initiatives -> boards (board_id));
diesel::joinable!(item_links -> forge_connections (connection_id));
diesel::joinable!(item_metadata -> metadata_definitions (metadata_definition_id));
diesel::joinable!(metadata_definition_scopes -> metadata_definitions (metadata_definition_id));
diesel::joinable!(metadata_enum_options -> metadata_definitions (metadata_definition_id));
diesel::joinable!(repositories -> teams (team_id));
diesel::joinable!(strategies -> board_columns (column_id));
diesel::joinable!(strategies -> boards (board_id));
diesel::joinable!(tasks -> board_columns (column_id));
diesel::joinable!(tasks -> boards (board_id));
diesel::joinable!(tasks -> repositories (repository_id));
diesel::joinable!(tasks -> teams (team_id));
diesel::joinable!(team_announcements -> teams (team_id));
diesel::joinable!(team_delivery_streams -> delivery_streams (delivery_stream_id));
diesel::joinable!(team_delivery_streams -> teams (team_id));
diesel::joinable!(team_members -> teams (team_id));
diesel::joinable!(team_page_history -> team_pages (page_id));
diesel::joinable!(team_pages -> teams (team_id));
diesel::joinable!(template_metadata -> metadata_definitions (metadata_definition_id));
diesel::joinable!(template_metadata -> templates (template_id));

diesel::allow_tables_to_appear_in_same_query!(
    activity_log,
    adrs,
    api_keys,
    board_columns,
    board_member_capabilities,
    board_transitions,
    boards,
    delivery_streams,
    documents,
    edge_proposals,
    forge_connections,
    initiatives,
    item_chunks,
    item_embeddings,
    item_history,
    item_links,
    item_metadata,
    item_relationships,
    metadata_definition_scopes,
    metadata_definitions,
    metadata_enum_options,
    repositories,
    scim_tokens,
    strategies,
    tasks,
    team_announcements,
    team_delivery_streams,
    team_members,
    team_page_history,
    team_pages,
    teams,
    template_metadata,
    templates,
);

diesel::table! {
    public.organization_members (organization_id, user_id) {
        organization_id -> Uuid,
        user_id -> Uuid,
        role -> Text,
        joined_at -> Timestamptz,
    }
}

diesel::table! {
    public.organizations (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    public.system_board_defaults (id) {
        id -> Uuid,
        board_level -> Text,
        #[sql_name = "columns"]
        columns_ -> Text,
        transitions -> Text,
    }
}

diesel::table! {
    public.system_metadata_definition_scopes (metadata_definition_id, entity_type) {
        metadata_definition_id -> Uuid,
        entity_type -> Text,
    }
}

diesel::table! {
    public.system_metadata_definitions (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        field_type -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    public.system_metadata_enum_options (id) {
        id -> Uuid,
        metadata_definition_id -> Uuid,
        value -> Text,
        position -> Int4,
    }
}

diesel::table! {
    public.system_template_metadata (id) {
        id -> Uuid,
        template_id -> Uuid,
        metadata_definition_id -> Uuid,
        default_value -> Nullable<Text>,
        required -> Bool,
    }
}

diesel::table! {
    public.system_templates (id) {
        id -> Uuid,
        name -> Text,
        slug -> Text,
        content -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    public.users (id) {
        id -> Uuid,
        external_id -> Text,
        email -> Text,
        display_name -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        kind -> Text,
        user_name -> Text,
    }
}

diesel::joinable!(organization_members -> organizations (organization_id));
diesel::joinable!(organization_members -> users (user_id));
diesel::joinable!(system_metadata_definition_scopes -> system_metadata_definitions (metadata_definition_id));
diesel::joinable!(system_metadata_enum_options -> system_metadata_definitions (metadata_definition_id));
diesel::joinable!(system_template_metadata -> system_metadata_definitions (metadata_definition_id));
diesel::joinable!(system_template_metadata -> system_templates (template_id));

diesel::allow_tables_to_appear_in_same_query!(
    organization_members,
    organizations,
    system_board_defaults,
    system_metadata_definition_scopes,
    system_metadata_definitions,
    system_metadata_enum_options,
    system_template_metadata,
    system_templates,
    users,
);
