#!/usr/bin/env python3
"""
Render the REST reference page from the OpenAPI spec (KAIROS-T-0170).

`docs/src/reference/rest-api.md` is GENERATED, never hand-edited. R4 demands
completeness — every parameter, return value, error, default and constraint —
across 77 operations and 132 schemas, which no human keeps true. The spec
itself is trustworthy input: `openapi.rs`'s
`registered_routes_and_spec_paths_match_exactly` already asserts it matches
the router.

The rule this has to work at is R1, not R4. KAIROS-T-0166's spec review found
that generation satisfies completeness, consistency and currency better than a
human can, and fails on "structure mirrors the structure of the product
itself, so location is predictable" — because a generator emits its source's
ordering. So this renderer does NOT walk `paths` in spec order. It groups by
the operation's tag, and orders the groups the way the product is shaped:
the five entity families, then the operations that work across all of them,
then the org and admin surfaces, then the deployment's own endpoints.

It emits one page PER GROUP rather than one enormous page. Measured: a
single page came to 3694 lines, of which the schema tables were 1501. mdBook
puts only chapter titles in the sidebar, so a reader landing on that page got
a wall of text and a hand-written table of contents — complete (R4) and
unnavigable (R1), which is the exact failure the spec warns generated
reference falls into. Split, each group is 130–783 lines and the sidebar
mirrors the product.

Usage:  python3 scripts/render-openapi.py [--check]

  (no flag)  write docs/src/reference/rest-api.md and reference/rest/*.md
  --check    exit 1 if any committed page differs from what the spec implies

Reads target/openapi.json, produced by
`cargo test -p kairos-server --test openapi write_spec_artifact`.
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPEC = REPO / "target" / "openapi.json"
INDEX = REPO / "docs" / "src" / "reference" / "rest-api.md"
PAGES = REPO / "docs" / "src" / "reference" / "rest"

# The product's own shape, which is what R1 asks for. Tags not listed here
# are appended alphabetically under "Other" — and their absence from this
# list is a signal that a new surface was added and this order needs a look.
GROUPS = [
    ("Work items", """The five entity families. Every one has the same shape —
list, get, create, update, delete — and the same optimistic-concurrency
contract on update (KAIROS-A-0004): submit the `version` you read, and a
concurrent edit gets 409 with the current entity in `details.current`.""",
     ["strategies", "initiatives", "tasks", "documents", "adrs"]),

    ("Across any work item", """Operations addressed by `{entity_type}` and a
short code, so they work uniformly across the five families.""",
     ["relationships", "metadata", "history", "cascade", "restore", "search"]),

    ("Boards and teams", """Board configuration, membership, and the team
structures that own boards.""",
     ["boards", "board-members", "teams", "team-pages", "delivery-streams",
      "members"]),

    ("Execution scope", """Repositories as first-class execution scope
(KAIROS-A-0019) and the git forges behind them.""",
     ["repositories", "forge"]),

    ("Tenant configuration", """Org-admin surfaces: the metadata and template
definitions that shape what work items can carry.""",
     ["metadata-definitions", "templates"]),

    ("Machine access", """Service accounts, their API keys, and the SCIM
tokens for directory sync.""",
     ["service-accounts", "scim-tokens"]),

    ("The deployment itself", """Activity, administration, and what the
deployment reports about itself.""",
     ["activity", "admin", "meta"]),
]


GENERATED_HEADER = """<!-- GENERATED by scripts/render-openapi.py from the OpenAPI spec.
     Do not edit: your changes will be overwritten, and CI fails when this
     file disagrees with the spec. To change it, change the
     `#[utoipa::path]` annotation on the handler. -->"""


def fail(message):
    print(f"render-openapi: {message}", file=sys.stderr)
    sys.exit(1)


def load_spec():
    if not SPEC.exists():
        fail(
            f"{SPEC.relative_to(REPO)} not found. Produce it with:\n"
            "  cargo test -p kairos-server --test openapi write_spec_artifact"
        )
    try:
        spec = json.loads(SPEC.read_text())
    except json.JSONDecodeError as e:
        fail(f"{SPEC.relative_to(REPO)} is not valid JSON: {e}")
    # Fail loudly rather than emitting a plausible empty page.
    if not spec.get("openapi"):
        fail("spec has no `openapi` version field")
    if not spec.get("paths"):
        fail("spec has no paths — refusing to write an empty reference page")
    return spec


def anchor(text):
    """mdBook's heading anchor: lowercase, non-alphanumerics to hyphens.

    `_` is NOT a non-alphanumeric here: mdBook's slugger keeps it. Folding it
    to a hyphen produced `#listenvelope-board` for a heading whose real id is
    `listenvelope_board`, so every generic-envelope schema link landed at the
    top of schemas.md instead of at the schema (KAIROS-T-0175).
    """
    slug = re.sub(r"[^a-z0-9_]+", "-", text.lower()).strip("-")
    return slug


def type_of(schema, spec):
    """A short, human type for a schema node."""
    if schema is None:
        return "—"
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        # Operation pages live beside schemas.md in reference/rest/, so the
        # link is a sibling page plus the schema's own heading anchor.
        return f"[`{name}`](schemas.md#{anchor(name)})"
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return type_of(schema["allOf"][0], spec)
    for key in ("oneOf", "anyOf"):
        if key in schema:
            inner = [type_of(s, spec) for s in schema[key]
                     if s.get("type") != "null"]
            nullable = any(s.get("type") == "null" for s in schema[key])
            joined = " or ".join(dict.fromkeys(inner)) or "—"
            return f"{joined}, nullable" if nullable else joined
    t = schema.get("type")
    if isinstance(t, list):
        non_null = [x for x in t if x != "null"]
        base = non_null[0] if non_null else "null"
        suffix = ", nullable" if "null" in t else ""
        return f"`{base}`{suffix}"
    if t == "array":
        return f"array of {type_of(schema.get('items'), spec)}"
    if t is None:
        return "—"
    if "enum" in schema:
        values = ", ".join(f"`{v}`" for v in schema["enum"])
        return f"`{t}` ({values})"
    return f"`{t}`"


def render_operation(method, path, op, spec, lines):
    summary = (op.get("summary") or "").strip()
    heading = f"`{method.upper()} {path}`"
    lines.append(f"### {heading}\n")
    if summary:
        lines.append(f"{summary}\n")
    desc = (op.get("description") or "").strip()
    if desc and desc != summary:
        lines.append(f"{desc}\n")

    params = op.get("parameters") or []
    if params:
        lines.append("| Parameter | In | Required | Type | Description |")
        lines.append("|---|---|---|---|---|")
        for p in params:
            req = "yes" if p.get("required") else "no"
            lines.append(
                f"| `{p.get('name')}` | {p.get('in')} | {req} "
                f"| {type_of(p.get('schema'), spec)} "
                f"| {(p.get('description') or '').replace(chr(10), ' ')} |"
            )
        lines.append("")

    body = op.get("requestBody")
    if body:
        content = body.get("content", {})
        for media, node in content.items():
            required = " (required)" if body.get("required") else ""
            lines.append(
                f"Request body{required}: `{media}`, "
                f"{type_of(node.get('schema'), spec)}\n"
            )

    responses = op.get("responses") or {}
    if responses:
        lines.append("| Response | Body | Meaning |")
        lines.append("|---|---|---|")
        for status in sorted(responses):
            node = responses[status] or {}
            schema = None
            for media_node in (node.get("content") or {}).values():
                schema = media_node.get("schema")
                break
            lines.append(
                f"| `{status}` | {type_of(schema, spec) if schema else '—'} "
                f"| {(node.get('description') or '').replace(chr(10), ' ')} |"
            )
        lines.append("")


def render(spec):
    paths = spec["paths"]
    # tag -> [(path, method, op)], each in path order within its tag
    by_tag = {}
    for path in sorted(paths):
        for method, op in paths[path].items():
            if not isinstance(op, dict) or method not in (
                "get", "put", "post", "delete", "patch", "head", "options"
            ):
                continue
            for tag in op.get("tags") or ["untagged"]:
                by_tag.setdefault(tag, []).append((path, method, op))

    known = {t for _, _, tags in GROUPS for t in tags}
    leftover = sorted(set(by_tag) - known)
    groups = list(GROUPS)
    if leftover:
        groups.append((
            "Other",
            "Surfaces added since this page's grouping was last reviewed — "
            "see `scripts/render-openapi.py`'s `GROUPS`.",
            leftover,
        ))

    info = spec.get("info") or {}
    out = {}
    lines = [
        GENERATED_HEADER,
        "",
        "# REST API",
        "",
        f"OpenAPI {spec['openapi']}"
        + (f", Kairos {info['version']}" if info.get("version") else "")
        + f". {len(paths)} paths, "
        + f"{len(spec.get('components', {}).get('schemas', {}))} schemas.",
        "",
        "Every endpoint is served under the tenant resolved from the request "
        "host and requires a bearer token; see "
        "[Configuration](configuration.md) for how a deployment resolves "
        "both. The live spec is at `/api/openapi.json`.",
        "",
        "This page is generated from that spec, so it cannot drift from the "
        "router — but it describes only *what exists*. For how to do "
        "something, see the how-to guides; for why the API is shaped this "
        "way, see the explanation pages.",
        "",
        "## Contents",
        "",
    ]

    for title, blurb, tags in groups:
        present = [t for t in tags if t in by_tag]
        if not present:
            continue
        count = sum(len(by_tag[t]) for t in present)
        slug = anchor(title)
        lines.append(
            f"- [{title}](rest/{slug}.md) — {count} operations. "
            + " ".join(blurb.split())
        )

        page = [
            GENERATED_HEADER,
            "",
            f"# {title}",
            "",
            " ".join(blurb.split()),
            "",
        ]
        for tag in present:
            page.append(f"## {tag}\n")
            for path, method, op in by_tag[tag]:
                render_operation(method, path, op, spec, page)
        out[f"rest/{slug}.md"] = "\n".join(page) + "\n"

    schemas = (spec.get("components") or {}).get("schemas") or {}
    if schemas:
        lines.append(
            f"- [Schemas](rest/schemas.md) — {len(schemas)} wire shapes, "
            "referenced from the operations above."
        )
        page = [
            GENERATED_HEADER,
            "",
            "# Schemas",
            "",
            "The wire shapes the operations reference, alphabetically. A "
            "field is optional unless marked required.",
            "",
        ]
        for name in sorted(schemas):
            node = schemas[name]
            page.append(f"## {name}\n")
            if node.get("description"):
                page.append(" ".join(node["description"].split()) + "\n")
            props = node.get("properties") or {}
            required = set(node.get("required") or [])
            if props:
                page.append("| Field | Type | Required | Description |")
                page.append("|---|---|---|---|")
                for field in sorted(props):
                    p = props[field]
                    req = "yes" if field in required else "no"
                    d = " ".join((p.get("description") or "").split())
                    page.append(
                        f"| `{field}` | {type_of(p, spec)} | {req} | {d} |"
                    )
                page.append("")
            elif node.get("enum"):
                values = ", ".join(f"`{v}`" for v in node["enum"])
                page.append(f"One of: {values}\n")
        out["rest/schemas.md"] = "\n".join(page) + "\n"

    lines.append("")
    out["rest-api.md"] = "\n".join(lines) + "\n"
    return out


def main():
    check = "--check" in sys.argv[1:]
    pages = render(load_spec())
    base = INDEX.parent

    if check:
        stale = []
        for rel, content in sorted(pages.items()):
            target = base / rel
            if not target.exists() or target.read_text() != content:
                stale.append(rel)
        # A page the spec no longer implies is stale too — an endpoint group
        # removed from the product must not leave a page behind.
        if PAGES.exists():
            expected = {r for r in pages if r.startswith("rest/")}
            for existing in sorted(PAGES.glob("*.md")):
                rel = f"rest/{existing.name}"
                if rel not in expected:
                    stale.append(f"{rel} (orphaned)")
        if stale:
            fail(
                "the generated REST reference is stale:\n  "
                + "\n  ".join(stale)
                + "\nRegenerate with:  angreal docs api\n"
                "These pages come from the OpenAPI spec; a handler's "
                "#[utoipa::path] annotation changed without them being "
                "re-rendered."
            )
        print(f"REST reference is current ({len(pages)} pages)")
        return 0

    PAGES.mkdir(parents=True, exist_ok=True)
    total = 0
    for rel, content in sorted(pages.items()):
        target = base / rel
        target.write_text(content)
        total += len(content.splitlines())
    # Remove any page the spec no longer implies.
    expected = {r for r in pages if r.startswith("rest/")}
    for existing in sorted(PAGES.glob("*.md")):
        if f"rest/{existing.name}" not in expected:
            existing.unlink()
            print(f"removed orphaned {existing.relative_to(REPO)}")
    print(f"wrote {len(pages)} pages, {total} lines total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
